nexell: Fix NullPointerException when BackupService is null
This patch fixes NullPointerException when enter to "Backup & reset" menu.

Following error is fixed.

E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.android.settings, PID: 693
E AndroidRuntime: java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.android.settings/com.android.settings.Settings$PrivacySettingsActivity}:
java.lang.NullPointerException: Attempt to invoke interface method 'boolean
android.app.backup.IBackupManager.isBackupEnabled()' on a null object reference
E AndroidRuntime:	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
E AndroidRuntime:	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
E AndroidRuntime:	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E AndroidRuntime:	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
E AndroidRuntime:	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime:	at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime:	at android.app.ActivityThread.main(ActivityThread.java:6121)
E AndroidRuntime:	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E AndroidRuntime:	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean
android.app.backup.IBackupManager.isBackupEnabled()' on a null object reference
E AndroidRuntime:	at com.android.settings.PrivacySettings.updateToggles(PrivacySettings.java:157)
E AndroidRuntime:	at com.android.settings.PrivacySettings.onCreate(PrivacySettings.java:111)
AndroidRuntime:	at android.app.Fragment.performCreate(Fragment.java:2336)
E AndroidRuntime:	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
E AndroidRuntime:	at android.app.BackStackRecord.setLastIn(BackStackRecord.java:860)
E AndroidRuntime:	at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:900)
E AndroidRuntime:	at android.app.BackStackRecord.run(BackStackRecord.java:728)
E AndroidRuntime:	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
E AndroidRuntime:	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:563)
E AndroidRuntime:	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:1035)
E AndroidRuntime:	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:623)
E AndroidRuntime:	at android.app.Activity.performCreate(Activity.java:6682)
E AndroidRuntime:	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
E AndroidRuntime:	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
E AndroidRuntime:	... 9 more

Change-Id: I4f04f6c2adf88e41191974a44062ca0b17a39bf0
Signed-off-by: Sungwoo Park <swpark@nexell.co.kr>